# Generated by Django 3.1.3 on 2020-11-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_num',
            new_name='customer',
        ),
    ]
